from enum import Enum


class CMD(Enum):
    PING = 0
    SEND_TWO_INTS = 1
    SEND_THREE_FLOATS = 2
    GET_TIME_MILLIS = 3
    ECHO = 4
    DANCE = 5
    SET_VEL = 6
    STORE_TIME_MILLIS = 7
    SEND_TIME_MILLIS = 8
    SEND_IMU_DATA = 9
    SEND_TOF_DATA = 10
    TOF_SHORT = 11
    TOF_LONG = 12
    TOF_STATS = 13
    START_RECORDING = 14
    STOP_RECORDING = 15
    MOTOR_CMD = 16
    MOTOR_STOP = 17
    SET_MOTOR_CAL = 18
    MOTOR_TEST_SEQ = 19
